name: Setup Java Development Kits built by Oracle
on: [pull_request]

steps:
  - name: 'Set up latest Oracle JDK 18'
    uses: oracle-actions/setup-java@v1
    with:
      website: oracle.com
      release: 18
