name: build
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package  -Dmaven.javadoc.skip=true verify -Dgpg.skip

      - name: Build and Run Tests
        run: mvn test # execute your tests generating test results
        
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.7.5
        if: always() # always run even if the previous step fails
        with:
          report_paths: target/surefire-reports/*.xml

      - name: Test Report - JUnit table
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JUnit Test results            # Name of the check run which will be created
          path: target/surefire-reports/*.xml    # Path to test results
          reporter: java-junit        # Format of test results

